import React from 'react';
import { 
  Leaf, Users, Layers, Sun, Home, Box, Search, 
  ChevronRight, ChevronDown, Plus, Trash2, Copy, 
  Save, Wand2, Image as ImageIcon, Upload, X,
  MoreVertical, RefreshCw, Star, Clock, LayoutGrid,
  PlusCircle, FileText, Eraser, Check, Settings, Edit2,
  Languages, Database, Download, FileJson, AlertTriangle,
  Package, LayoutTemplate, Brain, Sparkles,
  MessageSquare, AppWindow, StickyNote, Laptop, Monitor,
  HelpCircle, Info, Code
} from 'lucide-react';

export const Icons = {
  Vegetation: Leaf,
  People: Users,
  Materials: Layers,
  Lighting: Sun,
  ArchStyle: Home,
  Details: Box,
  Box,
  Search,
  ChevronRight,
  ChevronDown,
  Plus,
  Trash: Trash2,
  Copy,
  Save,
  Magic: Wand2,
  Image: ImageIcon,
  Upload,
  Close: X,
  More: MoreVertical,
  Refresh: RefreshCw,
  Star,
  Clock,
  Library: LayoutGrid,
  LayoutGrid,
  PlusCircle,
  FileText,
  Eraser,
  Check,
  Settings,
  Edit: Edit2,
  Languages,
  Database,
  Download,
  FileJson,
  AlertTriangle,
  Package,
  Template: LayoutTemplate,
  LayoutTemplate,
  Brain,
  Sparkles,
  Comments: MessageSquare,
  Note: StickyNote,
  App: AppWindow,
  Software: Monitor,
  Laptop,
  Help: HelpCircle,
  Info,
  Code
};